### ISSUE TITLE
Question: Is the HTTP2 server fully implemented and tested against the HTTP2 specs?

### ISSUE THREAD

**Issue by eliasjpr** [jgaskins/grpc#1]

**Comment by jgaskins** [comment]
It only has enough of HTTP/2 implemented to handle the simplest gRPC request/response model right now. I've experimented with the idea of adding support for streaming gRPC requests and responses, but I'm not trying to build a general-purpose HTTP/2 library.

If that's what you're looking for, check out [the `ysbaddaden/http2` shard](https://github.com/ysbaddaden/http2). It's incomplete and still needs a little bit of work to be used from outside itself, but it _is_ tested against the HTTP/2 specs and is a general-purpose HTTP/2 library.
